---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-collection-dev
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: policy-collection
    policy-collection/environment: dev
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_ORG/policy-collection-consolidation.git
    targetRevision: master
    path: environments/dev
    kustomize:
      buildOptions: --enable-alpha-plugins --enable-helm
  destination:
    server: https://kubernetes.default.svc
    namespace: acm-policies-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
