---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: tutorial-policies
  namespace: openshift-gitops
spec:
  kustomizeBuildOptions: --enable-alpha-plugins
  server:
    route:
      enabled: true
  repo:
    env:
      - name: KUSTOMIZE_PLUGIN_HOME
        value: /etc/kustomize/plugin
    initContainers:
      - name: policy-generator-install
        image: registry.redhat.io/rhacm2/multicluster-operators-subscription-rhel9:v2.14
        command:
          - sh
          - -c
        args:
          - >-
            cp /etc/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator/PolicyGenerator
            /policy-generator/PolicyGenerator && chmod +x /policy-generator/PolicyGenerator
        volumeMounts:
          - name: policy-generator
            mountPath: /policy-generator
    volumeMounts:
      - name: policy-generator
        mountPath: /etc/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator
    volumes:
      - name: policy-generator
        emptyDir: {}
